version: '3.8'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - frontend
