{{- if .Values.certmanager.enabled }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-issuer
  namespace: informed
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: itsrahulrajesh@gmail.com
    privateKeySecretRef:
      name: cert-manager-letsencrypt
    # Add a single challenge solver, HTTP01 using nginx
    solvers:
      - dns01:
          cloudDNS:
            project: {{ .Values.certificates.solver }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: app-certificate
  namespace: informed
spec:
  secretName: app-certificate
  issuerRef:
    name: letsencrypt-issuer
    kind: ClusterIssuer
  dnsNames:
    - {{ .Values.hostname }}
{{- end }}
