{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "informed-core.fullname" . }}-ingress
  annotations:
    {{- if .Values.ingress.annotations }}
    {{- toYaml .Values.ingress.annotations | nindent 4 }}
    {{- end }}
    # These annotations enforce HTTPS
    kubernetes.io/ingress.allow-http: "false"
    networking.gke.io/managed-certificates: {{ include "informed-core.fullname" . }}-cert
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
  - host: {{ .Values.hostname }}
    http:
      paths:
      - path: /api     # This means all API calls need /api prefix
        pathType: Prefix
        backend:
          service:
            name: {{ include "informed-core.fullname" . }}-core
            port:
              number: {{ .Values.service.core.port }}
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ include "informed-core.fullname" . }}-ui
            port:
              number: {{ .Values.service.ui.port }}
{{- end }}
