{{- if .Values.image.pullSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.image.pullSecretName }}
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Values.image.pullSecret }}
{{- end }}
