apiVersion: v1
kind: Service
metadata:
  name: informed-redis
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "informed-core.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
spec:
  ports:
    - port: 6379
      targetPort: redis
      protocol: TCP
      name: redis
  selector:
    {{- include "informed-core.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: redis
